# Generated by Django 4.2.7 on 2025-08-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Webhook endpoint called', max_length=200)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('invalid', 'Invalid')], max_length=10)),
                ('status_code', models.IntegerField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status'], name='sms_webhook_status_6a1f49_idx'), models.Index(fields=['received_at'], name='sms_webhook_receive_61febf_idx'), models.Index(fields=['endpoint'], name='sms_webhook_endpoin_848ffa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(help_text='Unique identifier from SMSMobileAPI', max_length=100, unique=True)),
                ('number', models.CharField(help_text='Phone number of sender/recipient', max_length=20)),
                ('message', models.TextField(help_text='SMS message content')),
                ('date', models.DateField(help_text='Date when SMS was received')),
                ('hour', models.TimeField(help_text='Hour when SMS was received')),
                ('time_received', models.DateTimeField(help_text='Full timestamp when SMS was received')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Original webhook payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ['-time_received'],
                'indexes': [models.Index(fields=['number'], name='sms_webhook_number_f79f7d_idx'), models.Index(fields=['time_received'], name='sms_webhook_time_re_f7f1eb_idx'), models.Index(fields=['status'], name='sms_webhook_status_7a46c5_idx'), models.Index(fields=['guid'], name='sms_webhook_guid_46e060_idx')],
            },
        ),
        migrations.CreateModel(
            name='MPESATransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='MPESA', max_length=20)),
                ('direction', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('paid', 'Paid')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tx_code', models.CharField(blank=True, help_text='MPESA transaction code', max_length=20)),
                ('tx_date', models.CharField(blank=True, help_text='Transaction date from SMS', max_length=20)),
                ('tx_time', models.CharField(blank=True, help_text='Transaction time from SMS', max_length=20)),
                ('tx_datetime_local', models.DateTimeField(blank=True, help_text='Combined transaction datetime', null=True)),
                ('parsing_confidence', models.FloatField(default=0.0, help_text='Confidence score of parsing (0-1)')),
                ('parsing_errors', models.JSONField(default=list, help_text='List of parsing errors if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='sms_webhook.smsmessage')),
            ],
            options={
                'verbose_name': 'MPESA Transaction',
                'verbose_name_plural': 'MPESA Transactions',
                'ordering': ['-tx_datetime_local', '-created_at'],
                'indexes': [models.Index(fields=['tx_code'], name='sms_webhook_tx_code_dff6be_idx'), models.Index(fields=['amount'], name='sms_webhook_amount_48d143_idx'), models.Index(fields=['direction'], name='sms_webhook_directi_73ad00_idx'), models.Index(fields=['tx_datetime_local'], name='sms_webhook_tx_date_9904c2_idx')],
            },
        ),
    ]
