# Generated by Django 4.2.7 on 2025-08-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
